<?php

namespace PHPSTORM_META {
    override(\Yaspa\Factory::make(0),
        map([
            \GuzzleHttp\Client::class => \GuzzleHttp\Client::class,
            \Yaspa\Builders\PagedResultsIterator::class => \Yaspa\Builders\PagedResultsIterator::class,
            \Yaspa\Responses\StatusCodes::class => \Yaspa\Responses\StatusCodes::class,
            \Yaspa\AdminApi\Customer\CustomerService::class => \Yaspa\AdminApi\Customer\CustomerService::class,
            \Yaspa\AdminApi\Customer\Builders\CountAllCustomersRequest::class => \Yaspa\AdminApi\Customer\Builders\CountAllCustomersRequest::class,
            \Yaspa\AdminApi\Customer\Builders\CustomerFields::class => \Yaspa\AdminApi\Customer\Builders\CustomerFields::class,
            \Yaspa\AdminApi\Customer\Builders\CreateAccountActivationUrlRequest::class => \Yaspa\AdminApi\Customer\Builders\CreateAccountActivationUrlRequest::class,
            \Yaspa\AdminApi\Customer\Builders\CreateNewCustomerRequest::class => \Yaspa\AdminApi\Customer\Builders\CreateNewCustomerRequest::class,
            \Yaspa\AdminApi\Customer\Builders\DeleteCustomerRequest::class => \Yaspa\AdminApi\Customer\Builders\DeleteCustomerRequest::class,
            \Yaspa\AdminApi\Customer\Builders\GetCustomerRequest::class => \Yaspa\AdminApi\Customer\Builders\GetCustomerRequest::class,
            \Yaspa\AdminApi\Customer\Builders\GetCustomersRequest::class => \Yaspa\AdminApi\Customer\Builders\GetCustomersRequest::class,
            \Yaspa\AdminApi\Customer\Builders\ModifyExistingCustomerRequest::class => \Yaspa\AdminApi\Customer\Builders\ModifyExistingCustomerRequest::class,
            \Yaspa\AdminApi\Customer\Builders\SearchCustomersRequest::class => \Yaspa\AdminApi\Customer\Builders\SearchCustomersRequest::class,
            \Yaspa\AdminApi\Customer\Builders\SendAccountInviteRequest::class => \Yaspa\AdminApi\Customer\Builders\SendAccountInviteRequest::class,
            \Yaspa\AdminApi\Customer\Transformers\AccountActivationUrl::class => \Yaspa\AdminApi\Customer\Transformers\AccountActivationUrl::class,
            \Yaspa\AdminApi\Customer\Transformers\Address::class => \Yaspa\AdminApi\Customer\Transformers\Address::class,
            \Yaspa\AdminApi\Customer\Transformers\Customer::class => \Yaspa\AdminApi\Customer\Transformers\Customer::class,
            \Yaspa\AdminApi\Customer\Transformers\CustomerInvite::class => \Yaspa\AdminApi\Customer\Transformers\CustomerInvite::class,
            \Yaspa\AdminApi\Metafield\Transformers\Metafield::class => \Yaspa\AdminApi\Metafield\Transformers\Metafield::class,
            \Yaspa\AdminApi\Product\Transformers\Product::class => \Yaspa\AdminApi\Product\Transformers\Product::class,
            \Yaspa\AdminApi\Product\Transformers\Image::class => \Yaspa\AdminApi\Product\Transformers\Image::class,
            \Yaspa\AdminApi\Product\Transformers\Variant::class => \Yaspa\AdminApi\Product\Transformers\Variant::class,
            \Yaspa\AdminApi\Shop\ShopService::class => \Yaspa\AdminApi\Shop\ShopService::class,
            \Yaspa\AdminApi\Shop\Transformers\Shop::class => \Yaspa\AdminApi\Shop\Transformers\Shop::class,
            \Yaspa\AdminApi\Shop\Builders\GetShopRequest::class => \Yaspa\AdminApi\Shop\Builders\GetShopRequest::class,
            \Yaspa\Authentication\Builders\ApiCredentials::class => \Yaspa\Authentication\Builders\ApiCredentials::class,
            \Yaspa\Authentication\Factory\ApiCredentials::class => \Yaspa\Authentication\Factory\ApiCredentials::class,
            \Yaspa\Authentication\OAuth\Builders\AccessTokenRequest::class => \Yaspa\Authentication\OAuth\Builders\AccessTokenRequest::class,
            \Yaspa\Authentication\OAuth\Builders\AuthorizePromptUri::class => \Yaspa\Authentication\OAuth\Builders\AuthorizePromptUri::class,
            \Yaspa\Authentication\OAuth\Builders\NewDelegateAccessTokenRequest::class => \Yaspa\Authentication\OAuth\Builders\NewDelegateAccessTokenRequest::class,
            \Yaspa\Authentication\OAuth\Builders\Scopes::class => \Yaspa\Authentication\OAuth\Builders\Scopes::class,
            \Yaspa\Authentication\OAuth\SecurityChecks::class => \Yaspa\Authentication\OAuth\SecurityChecks::class,
            \Yaspa\Authentication\OAuth\OAuthService::class => \Yaspa\Authentication\OAuth\OAuthService::class,
            \Yaspa\Authentication\OAuth\Transformers\AccessToken::class => \Yaspa\Authentication\OAuth\Transformers\AccessToken::class,
            \Yaspa\Authentication\OAuth\Transformers\AssociatedUser::class => \Yaspa\Authentication\OAuth\Transformers\AssociatedUser::class,
            \Yaspa\Authentication\OAuth\Transformers\AuthorizationCode::class => \Yaspa\Authentication\OAuth\Transformers\AuthorizationCode::class,
            \Yaspa\Authentication\OAuth\Transformers\Scopes::class => \Yaspa\Authentication\OAuth\Transformers\Scopes::class,
            \Yaspa\Authentication\PrivateAuthentication\Transformers\Credentials::class => \Yaspa\Authentication\PrivateAuthentication\Transformers\Credentials::class,
        ]));
}
